version: "3.8"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"    # interface web : http://localhost:15672

  gateway:
    build: ./gateway
    ports:
      - "3000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  identity-service:
    build: ./services/identity-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  search-service:
    build: ./services/search-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  catalog-service:
    build: ./services/catalog-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  booking-service:
    build: ./services/booking-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - db
      - rabbitmq

  interaction-service:
    build: ./services/interaction-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  admin-service:
    build: ./services/admin-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway

volumes:
  postgres_data: