version: "3.9"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  identity-service:
    build:
      context: .
      dockerfile: services/identity-service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  catalog-service:
    build:
      context: .
      dockerfile: services/catalog-service/Dockerfile
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      
  search-service:
    build:
      context: .
      dockerfile: services/search-service/Dockerfile
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  booking-service:
    build:
      context: .
      dockerfile: services/booking-service/Dockerfile
    ports:
      - "8005:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      - db
      - rabbitmq

  admin-service:
    build:
      context: .
      dockerfile: services/admin-service/Dockerfile
    ports:
      - "8005:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  frontend:
   build: ./frontend
   ports:
     - "5173:5173"
   depends_on:
     - gateway

volumes:
  postgres_data:

#  catalog-service:
#    build: ./services/catalog-service
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#    depends_on:
#      - db
#
#  interaction-service:
#    build: ./services/interaction-service
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#    depends_on:
#      - db
#
#  admin-service:
#    build: ./services/admin-service
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#    depends_on:
#      - db
#