services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  identity-service:
    build:
      context: .
      dockerfile: services/identity-service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  catalog-service:
    build:
      context: .
      dockerfile: services/catalog-service/Dockerfile
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      
  search-service:
    build:
      context: .
      dockerfile: services/search-service/Dockerfile
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  booking-service:
    build:
      context: .
      dockerfile: services/booking-service/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CATALOG_SERVICE_URL: http://catalog-service:8000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - catalog-service
      - rabbitmq

  admin-service:
    build:
      context: .
      dockerfile: services/admin-service/Dockerfile
    ports:
      - "8006:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway

  interaction-service:
    build:
      context: .
      dockerfile: services/interaction-service/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    ports:
      - "8007:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
      SMTP_FROM: noreply@rentalapp.local
    depends_on:
      - db
      - rabbitmq
      - mailhog

volumes:
  postgres_data:

#  catalog-service:
#    build: ./services/catalog-service
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#    depends_on:
#      - db
#

#
#  admin-service:
#    build: ./services/admin-service
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#    depends_on:
#      - db
#
